version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot:
    build: .
    container_name: springboot-container
    depends_on:
      - mysql
    ports:
      - "9999:9999"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql-data:
